name: vcf2mat
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - pandas>=1.1.3
  - numpy>=1.19.2
  - pysam>=0.15.3
  - joblib>=0.17.0
  - python
  - tqdm>=4.51.0
  - scipy>=1.5.2
  - numpy-base
  - polars
